name: Makefile CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - run: go version
    
    - name: Install protobuf compiler
      run: sudo apt install -y protobuf-compiler

    - name: Install protoc-gen-go plugin
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
    
    - name: Install protoc-gen-go-grpc pluign
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Update PATH for protoc to find the plugins
      run: export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Generate code from protobuf
      run: make proto
      
    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

    - name: Run linter
      run: make lint
      
    - name: Run unit tests
      run: make test
